name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        description: "Build status"
        required: false
        default: "success"
        options:
          - success
          - failure
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: |
          echo "status=${{ github.event.inputs.build-status }}" >> $GITHUB_OUTPUT
          echo "output1=value1" >> $GITHUB_OUTPUT
          echo "output2=value2" >> $GITHUB_OUTPUT
          cat "$GITHUB_OUTPUT"
      - name: Step with mistake
        run: |
          echo "mistake=true" > "$GITHUB_OUTPUT"
      - name: Print contents of GITHUB_OUTPUT
        run: cat "$GITHUB_OUTPUT"
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
  deploy:
    name: deploy
    needs: build
    if: ${{ needs.build.result == 'success' && needs.build.outputs.build-status == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy the application"
      - name: Print Outputs
        run: echo ${{ needs.build.outputs.output1 }}
