name: 17 - 1 - Custom Actions - Composite
on:
  workflow_dispatch:
    inputs:
      target-env:
        description: "Environment"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod
env:
  working-directory: "17-custom-actions/react-app"
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ github.event.inputs.target-env }}
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          target-env: ${{ github.event.inputs.target-env }}
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
